# Nome do Workflow: Aparecerá na aba "Actions" do seu repositório GitHub.
name: Build Storia ERP Installer for Windows

# Gatilhos: Define quando o workflow será executado.
on:
  # Executa em pushes para a branch 'main'.
  push:
    branches: [ "main" ]
  
  # Permite que você execute este workflow manualmente a partir da aba Actions.
  workflow_dispatch:

# Trabalhos: Define uma ou mais tarefas a serem executadas.
jobs:
  build:
    # Ambiente: Especifica que o trabalho deve ser executado em uma máquina virtual Windows.
    runs-on: windows-latest

    # Passos: A sequência de tarefas que compõem o trabalho.
    steps:
      # 1. Checkout do Código
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configurar o SDK do .NET
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      # 3. Instalar as Cargas de Trabalho do .NET MAUI
      - name: Install MAUI Workloads
        run: dotnet workload install maui

      # 4. Restaurar Dependências NuGet
      - name: Restore NuGet packages
        run: dotnet restore Storia.sln

      # 5. Publicar o Aplicativo como um Pacote MSIX
      # A saída será direcionada para uma pasta chamada 'publish' na raiz do repositório.
      - name: Publish MAUI App for Windows
        run: dotnet publish src/UI/Storia.UI.Maui/Storia.UI.Maui.csproj -c Release -f net8.0-windows10.0.19041.0 -o ./publish

      # 6. Carregar o Instalador MSIX como Artefato
      - name: Upload MSIX Installer
        uses: actions/upload-artifact@v4
        with:
          name: storia-erp-installer
          # CORREÇÃO: Este padrão é mais robusto. Ele procura por qualquer arquivo .msix
          # dentro da pasta 'publish' e de todas as suas subpastas.
          # Isso elimina a necessidade de saber a estrutura exata (bin/Release/etc.).
          path: './publish/**/*.msix'
