name: Build Storia ERP Installer for Windows

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Install MAUI Workloads
        run: dotnet workload install maui

      - name: Restore NuGet packages
        run: dotnet restore Storia.sln

      - name: Publish MAUI App for Windows
        run: dotnet publish src/UI/Storia.UI.Maui/Storia.UI.Maui.csproj -f net8.0-windows10.0.19041.0 -c Release -p:WindowsPackageType=MSIX -p:GenerateAppxPackageOnBuild=true -o ./publish

      - name: Upload MSIX Installer
        uses: actions/upload-artifact@v4
        with:
          name: storia-erp-installer
          path: '**/AppPackages/**/*.msix'
