name: Build e Pacote MSIX para Storia ERP

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Install MAUI Workloads
        run: dotnet workload install maui

      - name: Restore NuGet packages
        run: dotnet restore Storia.sln

      - name: Create Test Certificate
        run: |
          Add-Type -AssemblyName System.Security
          $cert = New-SelfSignedCertificate -DnsName "CN=TruveSoftware" -CertStoreLocation "Cert:\CurrentUser\My" -KeySpec KeyExchange -Type CodeSigningCert
          $password = ConvertTo-SecureString -String "1234" -Force -AsPlainText
          Export-PfxCertificate -Cert $cert -FilePath ".\storia_cert.pfx" -Password $password
        shell: pwsh

      - name: Publish MSIX Package
        run: >
          dotnet publish src/UI/Storia.UI.Maui/Storia.UI.Maui.csproj 
          -f net8.0-windows10.0.19041.0 
          -c Release 
          -p:WindowsPackageType=MSIX 
          -p:WindowsAppPackageVersion=1.0.${{ github.run_number }} 
          -p:AppxPackageSigningEnabled=true 
          -p:PackageCertificateThumbprint="" 
          -p:PackageCertificatePath=".\storia_cert.pfx" 
          -p:PackageCertificatePassword="1234"
        shell: pwsh
#sla
      - name: Upload MSIX Artifact
        uses: actions/upload-artifact@v4
        with:
          name: storia-erp-installer
          path: src/UI/Storia.UI.Maui/bin/Release/net8.0-windows10.0.19041.0/win10-x64/AppPackages/
